version: "3.9"
services:
  post.service:
    container_name: post.service
    image: ${DOCKER_REGISTRY-}postservice
    build:
      context: .
      dockerfile: PostService/Dockerfile
    networks: 
      - system-design
    environment:
      - ConnectionStrings__CosmosDB=AccountEndpoint=CONNECTION_STRING
      - AssetService=http://web.apigateway/assets

  asset.service:
    container_name: asset.service
    image: ${DOCKER_REGISTRY-}assetservice
    build:
      context: .
      dockerfile: AssetService/Dockerfile
    networks: 
      - system-design
    environment:
      - AzureWebJobsStorage=CONNECTION_STRING
      - StorageAccountName=
      - StorageAccountKey=

  reaction.service:
    container_name: reaction.service
    image: ${DOCKER_REGISTRY-}reactionservice
    build:
      context: .
      dockerfile: LikeService/Dockerfile
    networks: 
      - system-design
    environment:
      - ConnectionStrings__CosmosDB=AccountEndpoint=CONNECTION_STRING
      - ConnectionStrings__ServiceBus=CONNECTION_STRING

  web.apigateway:
    container_name: web.apigateway
    image: ${DOCKER_REGISTRY-}webapigateway
    build:
      context: .
      dockerfile: WebApiGateway/Dockerfile
    environment: 
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8082:80
    networks: 
      - system-design
    mem_limit: 100M
    mem_reservation: 50M

volumes:
  data01:
    driver: local

networks: 
  system-design:
    driver: bridge